defaults:
  thresholds:
    StartHesitation: 0.3
    Turn: 0.3
    Walking: 0.3
  hysteresis:
    start: 0.6
    continue: 0.4
  min_duration_s: 0.3
  merge_gap_s: 0.5

domains:
  defog:
    thresholds:
      StartHesitation: 0.28
      Turn: 0.28
      Walking: 0.28
    min_duration_s: 0.4
    merge_gap_s: 0.6
  tdcsfog:
    thresholds:
      StartHesitation: 0.32
      Turn: 0.32
      Walking: 0.32
    min_duration_s: 0.2
    merge_gap_s: 0.4

thresholds:
  StartHesitation: 0.6
  Turning: 0.6
  Walking: 0.6
hysteresis:
  start: 0.6
  continue: 0.4
min_duration_s: 0.3
merge_gap_s: 0.5
iou_nms: 0.5
